Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  
  config.vm.synced_folder ".", "/vagrant", create: true
  config.vm.synced_folder "./shared", "/shared", create: true
  config.vm.synced_folder "../stack", "/vagrant/stacks", create: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.check_guest_additions = false
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "shell", path: "scripts/provision.sh"
  
  config.vm.define "manager" do |m|
    m.vm.hostname = "swarm-manager"
    m.vm.network "private_network", ip: "192.168.56.10"

    m.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "swarm-manager"
    end

    m.vm.provision "shell", path: "scripts/provision-manager.sh"
  end
  
  (1..2).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.hostname = "swarm-worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.56.#{i + 10}"

      worker.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.name = "swarm-worker-#{i}"
      end

      worker.vm.provision "shell", path: "scripts/provision-worker.sh"
    end
  end
end