version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chargerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chargeflow-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

networks:
  chargeflow-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local