//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.01.06 at 11:59:08 AM UTC 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://dac.com/chargeproxy", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dac.chargeproxy;
